language: php

php:
  - 5.3
  - 5.4

before_install:
 - composer install
 - wget http://cs.sensiolabs.org/get/php-cs-fixer.phar

script:
 - phpunit

notifications:
  jabber: heiglandreas@jabber.org
  email : true